image: eclipse-temurin:17

stages:
  - build
  - run

build:
  stage: build
  script:
    - javac HelloWorld.java
  artifacts:
    paths:
      - HelloWorld.class

run:
  stage: run
  script:
    - java HelloWorld
